from . import product_category_ept
from . import product_ept
from . import product_uom_category_ept
from . import product_uom_ept
from . import res_partner_ept
from . import sale_order_ept
from . import sale_orderline_ept
from . import crm_team_ept
from . import crm_lead_ept
from . import crm_lead_line_ept
from . import stock_warehouse_ept
from . import stock_location_ept
from . import stock_picking_ept
from . import stock_move_ept
from . import purchase_order_ept
from . import purchase_order_line_ept
from . import stock_inventory_ept
from . import stock_inventory_line_ept
